### ISSUE TITLE
Choosing the wrong waypoint

### ISSUE THREAD

**Issue by sootysax** [CourseplayPathEditor/CoursePlay-Editor-6#8]
I'm finding since the last update (v17) that I'm having a really hard time clicking the correct waypoint..   I've been hovering over and clicking the end point to move it, and it's selecting a waypoint earlier in the course, WAY far away from where I'm clicking.

This was a big problem in the early FS15 version of CP editor..  i feel like it's gotten way worse since the last update.

**Comment by PromGames** [comment]
Yes, that's right. It is our bottle neck, we are looking to improve it, however, I will take a closer look.

It is question of pointing offset? I mean, you point far from WP to get selected?
Did you use circle to size 3, maybe that helps.
Prom

**Comment by alpha117** [comment]
I'm also having the same issue

**Comment by alpha117** [comment]
Example
![image](https://user-images.githubusercontent.com/30005040/53258004-73277880-36c3-11e9-8710-372f39d38513.png)

I cannot select the WP(red), it will always select the WP (blue)

**Comment by TinyCrocodile** [comment]
Already fixed in coursedrawer  just need to copy over

**Comment by TinyCrocodile** [comment]
Just for info. The problem was, that the selecting radius is not changed when zooming. I added the fix to a branch and will merge request this evening.

**Comment by alpha117** [comment]
Thanks, will the next update be available later this evening?

**Comment by alpha117** [comment]
Fixed in #18 , here now OK

**Comment by PromGames** [comment]
Good, we can also communicate in gitter, I have open a chat there 

[https://gitter.im/CoursePlay-Editor-6/community?utm_source=share-link&utm_medium=link&utm_campaign=share-link](url)

**Comment by alpha117** [comment]
Link does not work, I just get ‘URL’ in address bar of browser, not the complete address

**Comment by sootysax** [comment]
this is still a problem for me in V.18 - it is very difficult to select a waypoint that is in a slow turn with many waypoints close together..   more often than not, when I click on a waypoint, it will move a different waypoint to the place where I clicked.

**Comment by sootysax** [comment]
this is still a problem for me in V.18 - it is very difficult to select a waypoint that is in a slow turn with many waypoints close together.. more often than not, when I click on a waypoint, it will move a different waypoint to the place where I clicked.

https://drive.google.com/file/d/1ynRvt0aAVvfKYAcYvdntio9kYIVQ9WTe/view?usp=sharing

**Comment by alpha117** [comment]
#19 still a slight issue when at high zoom levels

**Comment by PromGames** [comment]
In version 20, the problem with selecting wp seems to be solved, however, you have to keep pressed the button of the mouse for a laps to get it selected and the you can move. Tiny is working on that and expect to get improved soon. 

Also we continue having flickering when zoom goes over 600, also in progress

Please give us feedback if the system of selecting has improved

**Comment by sootysax** [comment]
v20 has fixed the problem for me..   the slight delay is not an issue for me..

**Comment by TinyCrocodile** [comment]
the delay should be exactly the windows doubleclicktime. so you can ajust if you ar a fast doubleclicker :-)
the delay was introduced to make a difference between just selecting a point and moving it. so the point is not accidentally moved

**Comment by alpha117** [comment]
all good here with #20
